new

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -45,30 +45,29 @@ jobs:
           name: test-report
           path: result.log
 
-      # Step 6: Install Docker Engine
       - name: Install Docker Engine
         uses: docker/setup-buildx-action@v2
         with:
           version: 'latest'
 
-      # Step 7: Log in to Docker Hub
       - name: Docker login
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      # Step 8: Build the Docker image
       - name: Build the Docker image
         run: |
           docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0 .
 
-      # Step 9: Test Docker image
       - name: Install Trivy
         run: |
+          set -e
           curl -sfl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -x
-          sudo mv ./trivy /usr/local/bin/trivy
-          # Ensure it's executable
+          # Check if the trivy binary is present
+          ls -l ./bin || echo "Trivy binary not found"
+          # Move the binary to the desired location
+          sudo mv ./bin/trivy /usr/local/bin/trivy
           sudo chmod +x /usr/local/bin/trivy
 
       - name: Verify Trivy installation
@@ -84,8 +83,7 @@ jobs:
         with:
           name: trivy-report
           path: trivy-scan-report.html
-      
-      # Step 10: Push the Docker image to Docker Hub
+
       - name: Push the Docker image to Docker Hub
         run: |
           docker push ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0
